version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: monthly
          time: "14:00"
          timezone: Europe/Paris
      open-pull-requests-limit: 10
      reviewers:
          - williamdes
    - package-ecosystem: composer
      directory: "/"
      schedule:
          interval: monthly
          time: "14:00"
          timezone: Europe/Paris
      open-pull-requests-limit: 10
      reviewers:
          - williamdes
