dist: trusty
language: php
sudo: required

before_install:
- openssl aes-256-cbc -K $encrypted_ab8f92ccaef0_key -iv $encrypted_ab8f92ccaef0_iv
  -in scripts/sudo-bot/keys.tar.enc -out scripts/sudo-bot/keys.tar -d
- tar -C scripts/sudo-bot/ -xvf scripts/sudo-bot/keys.tar
before_script:
- "./scripts/ci/install-reporters.sh"
- "./scripts/ci/install.sh"
script:
- ./scripts/ci/ci-$CI_TYPE.sh
install:
- flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest
  --no-progress"
- composer install $flags
after_success:
- bash <(curl -s https://codecov.io/bash)
after_script:
- "./codacy-coverage.phar clover build/logs/clover.xml"
stages:
  - name: tests
    if: NOT type = cron
  - name: robot
    if: type = cron
jobs:
  include:
    - stage: tests
      php: '7.2'
      env: CI_TYPE=phpstan
      name: "PHPSTAN - PHP 7.2"
    - stage: tests
      php: '7.2'
      env: CI_TYPE=phpcs
      name: "PHPCS - PHP 7.1"
    - stage: tests
      php: '7.1'
      env: CI_TYPE=phpunit
      name: "PHPUNIT - PHP 7.1"
    - stage: tests
      php: '7.2'
      env: CI_TYPE=phpunit
      name: "PHPUNIT - PHP 7.2"
    - stage: tests
      os: osx
      language: generic
      php: '7.2'
      env: CI_TYPE=phpunit
      name: "PHPUNIT - PHP 7.2"
      before_install:
        - "./scripts/ci/install-osx.sh"
    - stage: robot
      php: '7.2'
      env: CI_TYPE=cron
      name: "Create a pull-request to update data"
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache/"
  - "$HOME/.cache/bower"
  - "$HOME/.npm"
  - "$HOME/.cache/ci"
  - "/var/cache/apt"
  - "~/Library/Caches/Homebrew"
addons:
  apt:
    update: false
git:
  submodules: false

deploy:
  - provider: script
    script: env TRAVIS_EVENT_TYPE=cron TRAVIS_PULL_REQUEST=false ./scripts/ci/ci-cron.sh
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+
