name: Run sudo-bot to update files

on:
    repository_dispatch:
        types: run-cron
    schedule:
        - cron: "30 13 * * 6"

jobs:
    run-sudo-bot-cron:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: yarn cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: composer cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install
              run: |
                  yarn install
                  composer install --no-interaction --prefer-dist --no-progress --no-suggest
            - name: Build
              run: |
                  yarn run build
                  composer run build
            - name: Run sudo-bot
              run: |
                  openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEY }} -iv ${{ secrets.ENCRYPTED_IV }} -in scripts/sudo-bot/keys.tar.enc -out scripts/sudo-bot/keys.tar -d
                  tar -C scripts/sudo-bot/ -xvf scripts/sudo-bot/keys.tar
                  rm scripts/sudo-bot/keys.tar
                  CWD=$(pwd)
                  cp scripts/sudo-bot/.env.ci scripts/sudo-bot/.env
                  sed -i "s,{{HOME}},${CWD},g" scripts/sudo-bot/.env
                  sed -i "s,{{GPG_PASSPHRASE}},${{ secrets.GPG_PASSPHRASE }},g" scripts/sudo-bot/.env
                  sed -i "s,{{INSTALLATION_ID}},${{ secrets.INSTALLATION_ID }},g" scripts/sudo-bot/.env
                  yarn run sudo-bot-pr
                  rm -f scripts/sudo-bot/.env
            - name: Run test
              run: |
                  yarn run test
                  composer run test
