name: Run tests

on: [push]

jobs:
    test-node:
        name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node_version: ["10", "12"]
                os: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node_version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - name: yarn cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - name: Install modules
              run: yarn install
            - name: Create setup files
              run: |
                  openssl aes-256-cbc -K ${{ secrets.ENCRYPTED_KEY }} -iv ${{ secrets.ENCRYPTED_IV }} -in scripts/sudo-bot/keys.tar.enc -out scripts/sudo-bot/keys.tar -d
                  tar -C scripts/sudo-bot/ -xvf scripts/sudo-bot/keys.tar
            - name: Run node tests
              run: |
                  yarn run test
                  yarn run report-coverage
            - name: Send coverage
              uses: codecov/codecov-action@v1

    test-php:
        name: Test on php ${{ matrix.php-version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php-version: ["7.1", "7.2", "7.3", "7.4", "8.0"]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: posix, mbstring
                  coverage: xdebug
                  tools: composer:v2
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              if: ${{ matrix.php-version != '8.0' }}
              run: composer install --no-interaction --prefer-dist --no-progress --no-suggest
            - name: Install dependencies for php 8.0
              if: ${{ matrix.php-version == '8.0' }}
              run: composer install --no-interaction --prefer-dist --no-progress --no-suggest --ignore-platform-reqs
            - name: Run php tests
              run: composer run test
            - name: Send coverage
              uses: codecov/codecov-action@v1
